// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: proto/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShoeService_AddShoe_FullMethodName             = "/com.liBong.shoeManager.service.ShoeService/addShoe"
	ShoeService_DeleteShoe_FullMethodName          = "/com.liBong.shoeManager.service.ShoeService/deleteShoe"
	ShoeService_UpdateShoe_FullMethodName          = "/com.liBong.shoeManager.service.ShoeService/updateShoe"
	ShoeService_SearchShoesPage_FullMethodName     = "/com.liBong.shoeManager.service.ShoeService/searchShoesPage"
	ShoeService_CountShoe_FullMethodName           = "/com.liBong.shoeManager.service.ShoeService/countShoe"
	ShoeService_ShoeById_FullMethodName            = "/com.liBong.shoeManager.service.ShoeService/shoeById"
	ShoeService_ShoesByIds_FullMethodName          = "/com.liBong.shoeManager.service.ShoeService/shoesByIds"
	ShoeService_BatchUpdateShoe_FullMethodName     = "/com.liBong.shoeManager.service.ShoeService/batchUpdateShoe"
	ShoeService_BatchAddAccountShoe_FullMethodName = "/com.liBong.shoeManager.service.ShoeService/batchAddAccountShoe"
	ShoeService_DeleteAccountShoe_FullMethodName   = "/com.liBong.shoeManager.service.ShoeService/deleteAccountShoe"
	ShoeService_SearchAccountShoes_FullMethodName  = "/com.liBong.shoeManager.service.ShoeService/searchAccountShoes"
)

// ShoeServiceClient is the client API for ShoeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoeServiceClient interface {
	AddShoe(ctx context.Context, in *AddShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteShoe(ctx context.Context, in *DeleteShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateShoe(ctx context.Context, in *UpdateShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchShoesPage(ctx context.Context, in *SearchShoesPageReq, opts ...grpc.CallOption) (*SearchShoesPageResp, error)
	CountShoe(ctx context.Context, in *CountShoesReq, opts ...grpc.CallOption) (*CountShoesResp, error)
	ShoeById(ctx context.Context, in *ShoeByIdReq, opts ...grpc.CallOption) (*ShoeByIdResp, error)
	ShoesByIds(ctx context.Context, in *ShoesByIdsReq, opts ...grpc.CallOption) (*ShoesByIdsResp, error)
	BatchUpdateShoe(ctx context.Context, in *BatchUpdateShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 用户关联
	BatchAddAccountShoe(ctx context.Context, in *BatchAddAccountShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAccountShoe(ctx context.Context, in *DeleteAccountShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchAccountShoes(ctx context.Context, in *SearchAccountShoesReq, opts ...grpc.CallOption) (*SearchAccountShoesResp, error)
}

type shoeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShoeServiceClient(cc grpc.ClientConnInterface) ShoeServiceClient {
	return &shoeServiceClient{cc}
}

func (c *shoeServiceClient) AddShoe(ctx context.Context, in *AddShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_AddShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) DeleteShoe(ctx context.Context, in *DeleteShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_DeleteShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) UpdateShoe(ctx context.Context, in *UpdateShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_UpdateShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) SearchShoesPage(ctx context.Context, in *SearchShoesPageReq, opts ...grpc.CallOption) (*SearchShoesPageResp, error) {
	out := new(SearchShoesPageResp)
	err := c.cc.Invoke(ctx, ShoeService_SearchShoesPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) CountShoe(ctx context.Context, in *CountShoesReq, opts ...grpc.CallOption) (*CountShoesResp, error) {
	out := new(CountShoesResp)
	err := c.cc.Invoke(ctx, ShoeService_CountShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) ShoeById(ctx context.Context, in *ShoeByIdReq, opts ...grpc.CallOption) (*ShoeByIdResp, error) {
	out := new(ShoeByIdResp)
	err := c.cc.Invoke(ctx, ShoeService_ShoeById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) ShoesByIds(ctx context.Context, in *ShoesByIdsReq, opts ...grpc.CallOption) (*ShoesByIdsResp, error) {
	out := new(ShoesByIdsResp)
	err := c.cc.Invoke(ctx, ShoeService_ShoesByIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) BatchUpdateShoe(ctx context.Context, in *BatchUpdateShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_BatchUpdateShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) BatchAddAccountShoe(ctx context.Context, in *BatchAddAccountShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_BatchAddAccountShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) DeleteAccountShoe(ctx context.Context, in *DeleteAccountShoeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShoeService_DeleteAccountShoe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoeServiceClient) SearchAccountShoes(ctx context.Context, in *SearchAccountShoesReq, opts ...grpc.CallOption) (*SearchAccountShoesResp, error) {
	out := new(SearchAccountShoesResp)
	err := c.cc.Invoke(ctx, ShoeService_SearchAccountShoes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoeServiceServer is the server API for ShoeService service.
// All implementations must embed UnimplementedShoeServiceServer
// for forward compatibility
type ShoeServiceServer interface {
	AddShoe(context.Context, *AddShoeReq) (*emptypb.Empty, error)
	DeleteShoe(context.Context, *DeleteShoeReq) (*emptypb.Empty, error)
	UpdateShoe(context.Context, *UpdateShoeReq) (*emptypb.Empty, error)
	SearchShoesPage(context.Context, *SearchShoesPageReq) (*SearchShoesPageResp, error)
	CountShoe(context.Context, *CountShoesReq) (*CountShoesResp, error)
	ShoeById(context.Context, *ShoeByIdReq) (*ShoeByIdResp, error)
	ShoesByIds(context.Context, *ShoesByIdsReq) (*ShoesByIdsResp, error)
	BatchUpdateShoe(context.Context, *BatchUpdateShoeReq) (*emptypb.Empty, error)
	// 用户关联
	BatchAddAccountShoe(context.Context, *BatchAddAccountShoeReq) (*emptypb.Empty, error)
	DeleteAccountShoe(context.Context, *DeleteAccountShoeReq) (*emptypb.Empty, error)
	SearchAccountShoes(context.Context, *SearchAccountShoesReq) (*SearchAccountShoesResp, error)
	mustEmbedUnimplementedShoeServiceServer()
}

// UnimplementedShoeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShoeServiceServer struct {
}

func (UnimplementedShoeServiceServer) AddShoe(context.Context, *AddShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShoe not implemented")
}
func (UnimplementedShoeServiceServer) DeleteShoe(context.Context, *DeleteShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShoe not implemented")
}
func (UnimplementedShoeServiceServer) UpdateShoe(context.Context, *UpdateShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShoe not implemented")
}
func (UnimplementedShoeServiceServer) SearchShoesPage(context.Context, *SearchShoesPageReq) (*SearchShoesPageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShoesPage not implemented")
}
func (UnimplementedShoeServiceServer) CountShoe(context.Context, *CountShoesReq) (*CountShoesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountShoe not implemented")
}
func (UnimplementedShoeServiceServer) ShoeById(context.Context, *ShoeByIdReq) (*ShoeByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShoeById not implemented")
}
func (UnimplementedShoeServiceServer) ShoesByIds(context.Context, *ShoesByIdsReq) (*ShoesByIdsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShoesByIds not implemented")
}
func (UnimplementedShoeServiceServer) BatchUpdateShoe(context.Context, *BatchUpdateShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateShoe not implemented")
}
func (UnimplementedShoeServiceServer) BatchAddAccountShoe(context.Context, *BatchAddAccountShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchAddAccountShoe not implemented")
}
func (UnimplementedShoeServiceServer) DeleteAccountShoe(context.Context, *DeleteAccountShoeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountShoe not implemented")
}
func (UnimplementedShoeServiceServer) SearchAccountShoes(context.Context, *SearchAccountShoesReq) (*SearchAccountShoesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAccountShoes not implemented")
}
func (UnimplementedShoeServiceServer) mustEmbedUnimplementedShoeServiceServer() {}

// UnsafeShoeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoeServiceServer will
// result in compilation errors.
type UnsafeShoeServiceServer interface {
	mustEmbedUnimplementedShoeServiceServer()
}

func RegisterShoeServiceServer(s grpc.ServiceRegistrar, srv ShoeServiceServer) {
	s.RegisterService(&ShoeService_ServiceDesc, srv)
}

func _ShoeService_AddShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).AddShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_AddShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).AddShoe(ctx, req.(*AddShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_DeleteShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).DeleteShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_DeleteShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).DeleteShoe(ctx, req.(*DeleteShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_UpdateShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).UpdateShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_UpdateShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).UpdateShoe(ctx, req.(*UpdateShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_SearchShoesPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShoesPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).SearchShoesPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_SearchShoesPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).SearchShoesPage(ctx, req.(*SearchShoesPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_CountShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountShoesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).CountShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_CountShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).CountShoe(ctx, req.(*CountShoesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_ShoeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShoeByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).ShoeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_ShoeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).ShoeById(ctx, req.(*ShoeByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_ShoesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShoesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).ShoesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_ShoesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).ShoesByIds(ctx, req.(*ShoesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_BatchUpdateShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).BatchUpdateShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_BatchUpdateShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).BatchUpdateShoe(ctx, req.(*BatchUpdateShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_BatchAddAccountShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAddAccountShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).BatchAddAccountShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_BatchAddAccountShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).BatchAddAccountShoe(ctx, req.(*BatchAddAccountShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_DeleteAccountShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountShoeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).DeleteAccountShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_DeleteAccountShoe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).DeleteAccountShoe(ctx, req.(*DeleteAccountShoeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoeService_SearchAccountShoes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAccountShoesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoeServiceServer).SearchAccountShoes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoeService_SearchAccountShoes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoeServiceServer).SearchAccountShoes(ctx, req.(*SearchAccountShoesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoeService_ServiceDesc is the grpc.ServiceDesc for ShoeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.liBong.shoeManager.service.ShoeService",
	HandlerType: (*ShoeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addShoe",
			Handler:    _ShoeService_AddShoe_Handler,
		},
		{
			MethodName: "deleteShoe",
			Handler:    _ShoeService_DeleteShoe_Handler,
		},
		{
			MethodName: "updateShoe",
			Handler:    _ShoeService_UpdateShoe_Handler,
		},
		{
			MethodName: "searchShoesPage",
			Handler:    _ShoeService_SearchShoesPage_Handler,
		},
		{
			MethodName: "countShoe",
			Handler:    _ShoeService_CountShoe_Handler,
		},
		{
			MethodName: "shoeById",
			Handler:    _ShoeService_ShoeById_Handler,
		},
		{
			MethodName: "shoesByIds",
			Handler:    _ShoeService_ShoesByIds_Handler,
		},
		{
			MethodName: "batchUpdateShoe",
			Handler:    _ShoeService_BatchUpdateShoe_Handler,
		},
		{
			MethodName: "batchAddAccountShoe",
			Handler:    _ShoeService_BatchAddAccountShoe_Handler,
		},
		{
			MethodName: "deleteAccountShoe",
			Handler:    _ShoeService_DeleteAccountShoe_Handler,
		},
		{
			MethodName: "searchAccountShoes",
			Handler:    _ShoeService_SearchAccountShoes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
