// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: proto/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DictService_AddDict_FullMethodName                = "/com.libong.commmon.service.dict.dictService/addDict"
	DictService_UpdateDict_FullMethodName             = "/com.libong.commmon.service.dict.dictService/updateDict"
	DictService_DeleteDict_FullMethodName             = "/com.libong.commmon.service.dict.dictService/deleteDict"
	DictService_DictByID_FullMethodName               = "/com.libong.commmon.service.dict.dictService/dictByID"
	DictService_SearchDictionariesPage_FullMethodName = "/com.libong.commmon.service.dict.dictService/searchDictionariesPage"
	DictService_CountDict_FullMethodName              = "/com.libong.commmon.service.dict.dictService/countDict"
	DictService_DictionariesByIds_FullMethodName      = "/com.libong.commmon.service.dict.dictService/dictionariesByIds"
)

// DictServiceClient is the client API for DictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictServiceClient interface {
	// 添加字典
	AddDict(ctx context.Context, in *AddDictReq, opts ...grpc.CallOption) (*AddDictResp, error)
	// 修改字典
	UpdateDict(ctx context.Context, in *UpdateDictReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除字典
	DeleteDict(ctx context.Context, in *DeleteDictReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 字典详情
	DictByID(ctx context.Context, in *DictByIDReq, opts ...grpc.CallOption) (*DictByIDResp, error)
	// 分页查询
	SearchDictionariesPage(ctx context.Context, in *SearchDictionariesPageReq, opts ...grpc.CallOption) (*SearchDictionariesPageResp, error)
	// 查询字典总数
	CountDict(ctx context.Context, in *CountDictReq, opts ...grpc.CallOption) (*CountDictResp, error)
	// 字典详情
	DictionariesByIds(ctx context.Context, in *DictionariesByIdsReq, opts ...grpc.CallOption) (*DictionariesByIdsResp, error)
}

type dictServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDictServiceClient(cc grpc.ClientConnInterface) DictServiceClient {
	return &dictServiceClient{cc}
}

func (c *dictServiceClient) AddDict(ctx context.Context, in *AddDictReq, opts ...grpc.CallOption) (*AddDictResp, error) {
	out := new(AddDictResp)
	err := c.cc.Invoke(ctx, DictService_AddDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) UpdateDict(ctx context.Context, in *UpdateDictReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictService_UpdateDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) DeleteDict(ctx context.Context, in *DeleteDictReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DictService_DeleteDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) DictByID(ctx context.Context, in *DictByIDReq, opts ...grpc.CallOption) (*DictByIDResp, error) {
	out := new(DictByIDResp)
	err := c.cc.Invoke(ctx, DictService_DictByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) SearchDictionariesPage(ctx context.Context, in *SearchDictionariesPageReq, opts ...grpc.CallOption) (*SearchDictionariesPageResp, error) {
	out := new(SearchDictionariesPageResp)
	err := c.cc.Invoke(ctx, DictService_SearchDictionariesPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) CountDict(ctx context.Context, in *CountDictReq, opts ...grpc.CallOption) (*CountDictResp, error) {
	out := new(CountDictResp)
	err := c.cc.Invoke(ctx, DictService_CountDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) DictionariesByIds(ctx context.Context, in *DictionariesByIdsReq, opts ...grpc.CallOption) (*DictionariesByIdsResp, error) {
	out := new(DictionariesByIdsResp)
	err := c.cc.Invoke(ctx, DictService_DictionariesByIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServiceServer is the server API for DictService service.
// All implementations must embed UnimplementedDictServiceServer
// for forward compatibility
type DictServiceServer interface {
	// 添加字典
	AddDict(context.Context, *AddDictReq) (*AddDictResp, error)
	// 修改字典
	UpdateDict(context.Context, *UpdateDictReq) (*emptypb.Empty, error)
	// 删除字典
	DeleteDict(context.Context, *DeleteDictReq) (*emptypb.Empty, error)
	// 字典详情
	DictByID(context.Context, *DictByIDReq) (*DictByIDResp, error)
	// 分页查询
	SearchDictionariesPage(context.Context, *SearchDictionariesPageReq) (*SearchDictionariesPageResp, error)
	// 查询字典总数
	CountDict(context.Context, *CountDictReq) (*CountDictResp, error)
	// 字典详情
	DictionariesByIds(context.Context, *DictionariesByIdsReq) (*DictionariesByIdsResp, error)
	mustEmbedUnimplementedDictServiceServer()
}

// UnimplementedDictServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDictServiceServer struct {
}

func (UnimplementedDictServiceServer) AddDict(context.Context, *AddDictReq) (*AddDictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDict not implemented")
}
func (UnimplementedDictServiceServer) UpdateDict(context.Context, *UpdateDictReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDict not implemented")
}
func (UnimplementedDictServiceServer) DeleteDict(context.Context, *DeleteDictReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDict not implemented")
}
func (UnimplementedDictServiceServer) DictByID(context.Context, *DictByIDReq) (*DictByIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictByID not implemented")
}
func (UnimplementedDictServiceServer) SearchDictionariesPage(context.Context, *SearchDictionariesPageReq) (*SearchDictionariesPageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDictionariesPage not implemented")
}
func (UnimplementedDictServiceServer) CountDict(context.Context, *CountDictReq) (*CountDictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountDict not implemented")
}
func (UnimplementedDictServiceServer) DictionariesByIds(context.Context, *DictionariesByIdsReq) (*DictionariesByIdsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionariesByIds not implemented")
}
func (UnimplementedDictServiceServer) mustEmbedUnimplementedDictServiceServer() {}

// UnsafeDictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictServiceServer will
// result in compilation errors.
type UnsafeDictServiceServer interface {
	mustEmbedUnimplementedDictServiceServer()
}

func RegisterDictServiceServer(s grpc.ServiceRegistrar, srv DictServiceServer) {
	s.RegisterService(&DictService_ServiceDesc, srv)
}

func _DictService_AddDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).AddDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_AddDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).AddDict(ctx, req.(*AddDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_UpdateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).UpdateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_UpdateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).UpdateDict(ctx, req.(*UpdateDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_DeleteDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).DeleteDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_DeleteDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).DeleteDict(ctx, req.(*DeleteDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_DictByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).DictByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_DictByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).DictByID(ctx, req.(*DictByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_SearchDictionariesPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDictionariesPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).SearchDictionariesPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_SearchDictionariesPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).SearchDictionariesPage(ctx, req.(*SearchDictionariesPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_CountDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).CountDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_CountDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).CountDict(ctx, req.(*CountDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_DictionariesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionariesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).DictionariesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_DictionariesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).DictionariesByIds(ctx, req.(*DictionariesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DictService_ServiceDesc is the grpc.ServiceDesc for DictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.libong.commmon.service.dict.dictService",
	HandlerType: (*DictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addDict",
			Handler:    _DictService_AddDict_Handler,
		},
		{
			MethodName: "updateDict",
			Handler:    _DictService_UpdateDict_Handler,
		},
		{
			MethodName: "deleteDict",
			Handler:    _DictService_DeleteDict_Handler,
		},
		{
			MethodName: "dictByID",
			Handler:    _DictService_DictByID_Handler,
		},
		{
			MethodName: "searchDictionariesPage",
			Handler:    _DictService_SearchDictionariesPage_Handler,
		},
		{
			MethodName: "countDict",
			Handler:    _DictService_CountDict_Handler,
		},
		{
			MethodName: "dictionariesByIds",
			Handler:    _DictService_DictionariesByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
